### ISSUE TITLE
seems gcp datastream for postgres bug

### ISSUE THREAD

**Issue by chandanshukla1989** [googleapis/java-datastream#258]
It seems gcp datastream for postgres source could not be created with gcloud and rest api command, but only in preview mode by UI..
When we are trying to create gcp datastream for postgres source with below gcloud command it results in an unexpected error while postgres replication slot and publication has been defined as per gcp documentation:
gcloud datastream streams create postgres-ds-stream-test1 --project=gcp-everwash-wh-dw --location=us-central1 --display-name=postgres-ds-display-1 --source=prod-conn-setup-1 --postgresql-source-config=files/config/datastream-source-postgresql1.json --destination=sbox-everwash-dwh-bigquery --bigquery-destination-config=files/config/datastream-destination-bigquery.json --backfill-none --validate-only

Error:
chandan_shukla@cloudshell:~ (gcp-everwash-wh-dw)$ gcloud datastream streams create postgres-ds-stream-test1 --project=gcp-everwash-wh-dw --location=us-central1 --display-name=postgres-ds-display-1 --source=prod-conn-setup-1 --postgresql-source-config=datastream-source-postgresql.yaml --destination=sbox-everwash-dwh-bigquery --bigquery-destination-config=datastream-destination-bigquery.json --backfill-none
ERROR: (gcloud.datastream.streams.create) INVALID_ARGUMENT: Request contains an invalid argument.

'@type': type.googleapis.com/google.rpc.BadRequest
fieldViolations:
description: Not specified
field: source_config.postgresql_source_config.publication
description: Not specified
field: source_config.postgresql_source_config.replication_slot
When we try rest api for the same with below command, it throws another weird error:
curl -X POST -H "Authorization: Bearer $(gcloud auth application-default print-access-token)" https://datastream.googleapis.com/v1/projects/gcp-everwash-wh-dw/locations/us-central1/streams?streamId=myPostgresStream1
{
"display_name": "PostgreSQL to Cloud Storage",
"source_config": {
"sourceConnectionProfileName": "/projects/gcp-everwash-wh-dw/locations/us-central1/streams/prod-conn-setup-1",
"postgresqlSourceConfig": {
"replicationSlot": "slot1",
"publication": "pub_1",
"includeObjects": {
"postgresqlSchemas": {
"schema": "internal",
"postgresqlTables": {
"table: "User1"
}
}
}
}
}
"destination_onfig": {
"destinationConnectionProfileName": "/projects/gcp-everwash-wh-dw/locations/us-central1/streams/sbox-everwash-dwh-bigquery
",
"gcsDestinationConfig": {
"avroFileFormat": "{}"
"fileRotationMb": 31
"fileRotationInterval": 100
}
},

"backfill_strategy": "None"
}

Error:
Here everything like source config etc.. has been defined, still it throws error

**Comment by diegomarquezp** [comment]
Hello @chandanshukla1989! 
As this is a CLI problem, this is out of the scope of the Java Datastream library. Please refer to the [CLI Documentation](https://cloud.google.com/cli) or contact [Customer Support](https://cloud.google.com/support-hub) for further assistance.
